package espresso.roslyn.boundtree;

import org.antlr.v4.runtime.ParserRuleContext;

/**
 * Object model to save the binding info generated by binder
 * */
public class BoundNode {
    final ParserRuleContext node;

    public BoundNode(ParserRuleContext node) {
        this.node = node;
    }
}
